# @package fixed

checkpoint_config:
  monitor: val/loss
  mode: min
  save_last: True

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

ood_dataset: uniform_noise

model_name: EnergyOOD
model_config:
  arch_name: fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.num_classes}
    hidden_dims: [100, 100, 100, 100, 100]
  learning_rate: 0.001
  weight_decay: 0.0
  momentum: 0.5
  checkpoint:
  # Needs to be set manually to path of a CE Baseline checkpoint
  m_in: -23
  m_out: -5
  score: energy
