# @package fixed

checkpoint_config:
  monitor: val/acc
  mode: max

earlystop_config:
  monitor: val/acc
  mode: max
  patience: 10

ood_dataset:

model_name: CEBaseline
model_config:
  arch_name: fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.num_classes}
    hidden_dims: [100, 100, 100, 100, 100]
    dropout: 0.3
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0005
