# @package fixed

checkpoint_config:
  monitor: val/acc
  mode: max

earlystop_config:
  monitor: val/acc
  mode: max
  patience: 10

ood_dataset:

model_name: PostNet
model_config:
  arch_name: fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.model_config.latent_dim}
    hidden_dims: [100, 100, 100, 100, 100]
  learning_rate: 0.001
  output_dim: ${fixed.num_classes}
  latent_dim: 10
  no_density: False
  density_type: radial_flow
  n_density: 8
  budget_function: id
  loss: UCE
  regr: 1.0e-5
