# @package fixed

checkpoint_config:
  monitor: val_acc
  mode: max

earlystop_config:
  monitor: val_acc
  mode: max
  patience: 10

ood_dataset: uniform_noise

model_name: PriorNet
model_config:
  arch_name: fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.num_classes}
    hidden_dims: [100, 100, 100, 100, 100]
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0
  target_concentration: 100.0
  concentration: 1.0
  gamma: 1.
  reverse_kl: True
  alpha_fix: True
