# @package fixed

trainer_config:
  max_epochs: 10_000
  max_steps: 10_000

earlystop_config:

checkpoint_config:
  monitor: val/acc
  mode: max
  save_last: True

ood_dataset: ${fixed.dataset}

model_name: SSM
model_config:
  arch_name: lipschitz_fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.num_classes}
    hidden_dims: [100, 100, 100]
    block_hidden_dims: [100, 100]
    coeff: 3.
    n_power_iterations: 1
    activation: relu

  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0
  clf_weight: 1.0
  n_classes: ${fixed.num_classes}
  noise_type: gaussian
  n_particles: 1
  warmup_steps: 2500
  lr_step_size: 1000
