# @package fixed

trainer_config:
  max_epochs: 100_000
  max_steps: 100_000

checkpoint_config:
  save_last: True

earlystop_config:

ood_dataset: ${fixed.dataset}

model_name: VERAPosteriorNet
model_config:
  arch_name: fc
  arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.num_classes}
    hidden_dims: [100, 100, 100, 100, 100]
    batch_norm: False
    bias: True
    slope: 0.2

  learning_rate: 0.0001
  beta1: 0.0
  beta2: 0.9
  weight_decay: 0.0
  n_classes: ${fixed.num_classes}
  uncond: False
  gen_learning_rate: 0.0002
  ebm_iters: 1
  generator_iters: 1
  entropy_weight: 1.0

  generator_type: vera
  generator_arch_name: fc
  generator_arch_config:
    inp_dim: ${fixed.data_shape.0}
    num_classes: ${fixed.data_shape.0}
    hidden_dims: [100, 100, 100, 100, 100]
    activation: relu
    batch_norm: True
    bias: False
  generator_config:
    noise_dim: ${fixed.data_shape.0}
    post_lr: 0.0002
    init_post_logsigma: 0.1

  min_sigma: 0.01
  max_sigma: 0.3
  p_control: 0.1
  n_control: ${fixed.model_config.p_control}
  pg_control: 0.1
  clf_ent_weight: 0.0
  ebm_type: jem
  clf_weight: 100.0
  warmup_steps: 2500
  no_g_batch_norm: False
  batch_size: ${fixed.batch_size}
  lr_decay: 1.
  lr_decay_epochs: [30, 35]
  vis_every: -1
  alpha_fix: True
  entropy_reg: 0.0
  sample_term: 0.0
