# @package fixed

checkpoint_config:
  monitor: val/acc
  mode: max

earlystop_config:
  monitor: val/acc
  mode: max
  patience: 10

model_name: CEBaseline
model_config:
  arch_name: lipschitz_wrn
  arch_config:
    depth: 16
    num_classes: ${fixed.num_classes}
    widen_factor: 8
    input_channels: ${fixed.data_shape.2}
    spectral_normalization: true
    coeff: 1.
    n_power_iterations: 1
    spatial_size: ${fixed.data_shape.0}
    negtive_linear: True
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
