# @package fixed

checkpoint_config:
  monitor: val/loss
  mode: min
  save_last: True

earlystop_config:
  monitor: val/loss
  mode: min
  patience: 10

ood_dataset: uniform_noise

model_name: EnergyOOD
model_config:
  arch_name: wrn
  arch_config:
    depth: 16
    num_classes: ${fixed.num_classes}
    widen_factor: 8
    input_channels: ${fixed.data_shape.2}
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  checkpoint:
  # Needs to be set manually to path of a CE Baseline checkpoint
  m_in: -23
  m_out: -5
  score: energy
