# @package fixed

checkpoint_config:
  monitor: val/acc
  mode: max

earlystop_config:
  monitor: val/acc
  mode: max
  patience: 10

model_name: MCDropout
model_config:
  arch_name: wrn
  arch_config:
    depth: 16
    num_classes: ${fixed.num_classes}
    widen_factor: 8
    input_channels: ${fixed.data_shape.2}
    dropout: 0.3
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
