# @package fixed

checkpoint_config:

earlystop_config:

ood_dataset: ${fixed.dataset}

model_name: VERA
model_config:
  n_classes: ${fixed.num_classes}
  arch_name: wrn
  arch_config:
    depth: 16
    num_classes: ${fixed.num_classes}
    widen_factor: 8
    input_channels: ${fixed.data_shape.2}
    strides: [1, 2, 2]
  learning_rate: 0.00003
  beta1: 0.0
  beta2: 0.9
  weight_decay: 0.0
  gen_learning_rate: 0.00006
  ebm_iters: 1
  generator_iters: 1
  entropy_weight: 0.0001
  generator_type: vera
  generator_arch_name: resnetgenerator
  generator_arch_config:
    unit_interval: False
    feats: 128
    out_channels: ${fixed.data_shape.2}
  generator_config:
    noise_dim: 128
    post_lr: 0.00003
    init_post_logsigma: 0.1
  min_sigma: 0.01
  max_sigma: 0.3
  p_control: 0.0
  n_control: 0.0
  pg_control: 0.1
  clf_ent_weight: 0.0001
  ebm_type: jem
  clf_weight: 100.0
  warmup_steps: 2500
  no_g_batch_norm: False
  batch_size: ${fixed.batch_size}
  lr_decay: 0.3
  lr_decay_epochs: [15, 18]
