# @package fixed

trainer_config:
  max_epochs: 40
  terminate_on_nan: True

checkpoint_config:
  monitor: val/acc
  mode: max
  save_last: True

earlystop_config:
  monitor: val/acc
  mode: max
  patience: 10

ood_dataset: ${fixed.dataset}
sigma: 0.01

model_name: VERAPosteriorNet
model_config:
  arch_name: wrn
  arch_config:
    depth: 4
    num_classes: ${fixed.num_classes}
    widen_factor: 10
    input_channels: ${fixed.data_shape.2}
    dropout: 0.3
    norm: group

  learning_rate: 0.00003
  beta1: 0.0
  beta2: 0.9
  weight_decay: 0.1
  n_classes: 10
  uncond: False
  gen_learning_rate: 0.00006
  ebm_iters: 1
  generator_iters: 1
  entropy_weight: 0.0001

  generator_type: vera
  generator_arch_name: resnetgenerator
  generator_arch_config:
    unit_interval: False
    feats: 128
    out_channels: ${fixed.data_shape.2}

  generator_config:
    noise_dim: 128
    post_lr: 0.00003
    init_post_logsigma: 0.1

  min_sigma: 0.01
  max_sigma: 0.3
  p_control: 1.0
  n_control: 1.0
  pg_control: 0.1
  clf_ent_weight: 0.1
  ebm_type: jem
  clf_weight: 1.0
  warmup_steps: 2500
  no_g_batch_norm: False
  batch_size: ${fixed.batch_size}
  lr_decay: 1.
  lr_decay_epochs: [30, 35]
  vis_every: -1
  alpha_fix: True
  entropy_reg: 0.0
  sample_term: 0.0
